### ISSUE TITLE
Setting SSL in config leads to NameError

### ISSUE THREAD

**Issue by Julian-O** [luk3yx/lurklite#1]
To reproduce, add a line like:
 
     ssl=false

to the config file. You will get a `NameError: name '_conf_bool' is not defined`

The offending line in core.py, line 230:

                if ssl:
                    kwargs['ssl'] = _conf_bool(section, ssl)
                    
That should read **self.**_conf_bool.

Forgive me for not setting up the complete development environment to submit a 5-character pull request. I figured it was much faster to let an existing contributor make the change.

**Comment by luk3yx** [comment]
Thanks for reporting this, I've created a new release with the fix.
