### ISSUE TITLE
Won't execute commands

### ISSUE THREAD

**Issue by hello-smile6** [luk3yx/lurklite#3]
```
<<< @time=2022-06-13T05:26:51.962Z :lurk MODE lurk :+Zi
<<< @time=2022-06-13T05:26:51.972Z :lurk!~23cbb3bc@users.solanum.repl JOIN #lurk
<<< @time=2022-06-13T05:26:51.972Z :solanum.repl 353 lurk = #lurk :lurk @_9pfs
<<< @time=2022-06-13T05:26:51.972Z :solanum.repl 366 lurk #lurk :End of /NAMES list.
<<< @+typing=active; :_9pfs TAGMSG #lurk
<<< @time=2022-06-13T05:26:57.239Z;account=_9pfs :_9pfs!~d8a05725@users.solanum.repl PRIVMSG #lurk :$help
help ['#lurk']
WARNING: Unable to read commands database! FileNotFoundError(2, 'No such file or directory')
>>> PRIVMSG #lurk :_9pfs: Invalid command: 'help'
<<< @+typing=active; :_9pfs TAGMSG #lurk
<<< @time=2022-06-13T05:26:59.529Z;account=_9pfs :_9pfs!~d8a05725@users.solanum.repl PRIVMSG #lurk :$time
time ['#lurk']
>>> PRIVMSG #lurk :_9pfs: Invalid command: 'time'
<<< @+typing=active; :_9pfs TAGMSG #lurk
<<< @time=2022-06-13T05:27:02.530Z;account=_9pfs :_9pfs!~d8a05725@users.solanum.repl PRIVMSG #lurk :$reply
reply ['#lurk']
>>> PRIVMSG #lurk :_9pfs: Invalid command: 'reply'
>>> PING :miniirc-ping
<<< @time=2022-06-13T05:28:02.593Z :solanum.repl PONG solanum.repl :miniirc-ping
```
The bot won't respond to commands. I'm using https://git.andrewyu.org/lurklite-commands/ for the commands.

**Comment by luk3yx** [comment]
Not all of the official lurklite bot's commands are in that repository, some of them are defined as "tempcmds". You could try `$tr`, `$wild`, `$fortune`, or `$r` for example.

**Comment by hello-smile6** [comment]
> Not all of the official lurklite bot's commands are in that repository, some of them are defined as "tempcmds". You could try `$tr`, `$wild`, `$fortune`, or `$r` for example.

What are the ones that are defined as tempcmds?

**Comment by luk3yx** [comment]
> > Not all of the official lurklite bot's commands are in that repository, some of them are defined as "tempcmds". You could try `$tr`, `$wild`, `$fortune`, or `$r` for example.
> 
> What are the ones that are defined as tempcmds?

There isn't a list of them anywhere, you could probably do `grep -r register_command /path/to/lurklite-commands` to see which commands are added in that Git repository.

**Comment by hello-smile6** [comment]
@luk3yx Would you accept contributions to the command list?

**Comment by luk3yx** [comment]
> @luk3yx Would you accept contributions to the command list?

That would depend on the feature and whether I want it in the official bot.
